development:
  adapter: postgresql
  database: risk_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: risk_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: risk_production
  pool: 5
  timeout: 5000